baseURL: https://tpalucki.github.io/
languageCode: en-us
title: Tomasz Pałucki

paginate: 5
theme: "PaperMod"
publishdir: docs/

enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-49627445-2

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Tomasz Pałucki
  description: "Tomasz Pałucki | Software developer - personal blog"
  author: Tomasz Pałucki
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  disableSpecial1stPost: false
  ShowPostNavLinks: true
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false
  ShowBreadCrumbs: true

  editPost:
    URL: "https://github.com/tpalucki/tpalucki.github.io/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  assets:
    #    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  #  label:
  #    text: "Home"
  #    icon: /apple-touch-icon.png
  #    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Tomasz Pałucki
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    #    - name: twitter
    #      url: "https://twitter.com/"
    #    - name: stackoverflow
    #      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/tpalucki"
    - name: linkedin
      url: "https://www.linkedin.com/in/tpalucki/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    #    - identifier: categories
    #      name: Categories
    #      url: /categories/
    #      weight: 10
    #    - identifier: tags
    #      name: Tags
    #      url: /tags/
    #      weight: 20
    #    - identifier: example
    #      name: Example.org
    #      url: https://example.org
    #      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 10

  # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
  # pygmentsUseClasses: true
#markup:
#  highlight:
#    # anchorLineNos: true
#    codeFences: true
#    guessSyntax: true
#    lineNos: true
#    style: monokai